id: P004281
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:07:12.660466
source_metadata:
  id: bdr:W8LS20263
  title: བོད་ཀྱི་ཁྱིམ་རྒྱུད་ཆེན་པོ་བཅུའི་སྐོར་གྱི་ངག་བརྗོད་ལོ་རྒྱུས།
  author: ''
  volumes:
    f1834a0a0f4246b3a14db16ea4ce3226:
      image_group_id: I8LS20265
      title: ''
      volume_number: 1
      total_pages: 399
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
