id: P004281
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20263
  title: བོད་ཀྱི་ཁྱིམ་རྒྱུད་ཆེན་པོ་བཅུའི་སྐོར་གྱི་ངག་བརྗོད་ལོ་རྒྱུས།
  author: ''
  volumes:
    f1834a0a0f4246b3a14db16ea4ce3226:
      image_group_id: I8LS20265
      title: ''
      volume_number: 1
      total_pages: 399
